import type {RuleScope} from '../src/jurisdictions';
/** Sources individually checked 2026-09-18. Selection is intentionally non-exhaustive. */
export const INTERNATIONAL_RULES: (RuleScope & {title: string; description: string; category: string; sourceName: string; sourceUrl: string; recurrence?: string})[] = [
  {country: 'AU', region: '', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'ASIC company annual review', description: 'For companies registered with ASIC: check the annual statement, pay the review fee by the date shown and check whether a solvency resolution is required. The fee is usually due two months after the review date. A financial-report exception can apply to the resolution. Use your own statement and the official guidance.', sourceName: 'ASIC', sourceUrl: 'https://www.asic.gov.au/for-business-and-companies/companies/company-annual-review/', recurrence: 'annual'},
  {country: 'AU', region: 'WA', industry: 'FoodService', category: 'Registration', title: 'WA food business registration or notification', description: 'Before operating, register or notify the relevant enforcement agency. Most food businesses deal with their local government; some are handled by WA Health. Exempt businesses may still need to notify. Registration generally continues until cancelled; do not assume an annual renewal. Check local fees and conditions separately.', sourceName: 'WA Department of Health', sourceUrl: 'https://www.health.wa.gov.au/articles/n_r/registration-of-a-food-business'},
  {country: 'AU', region: 'WA', locality: 'city-of-perth', industry: 'FoodService', category: 'Registration', title: 'City of Perth food premises approval', description: 'For premises inside the City of Perth council area, confirm whether registration or notification is required. New fit-outs and structural changes may need building or planning approval before food-business approval. Contact the City about the form appropriate to your premises. This does not cover the whole Perth metropolitan area.', sourceName: 'City of Perth', sourceUrl: 'https://perth.wa.gov.au/forms-and-payments/residents-and-businesses/Business/certification-and-approval/food-business-registration'},
  {country: 'GB', region: '', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'Companies House confirmation statement', description: 'For UK limited companies: review company information and submit a confirmation statement at least once every twelve months. Confirm the review period, filing deadline and identity-verification requirements with Companies House. This is separate from annual accounts and tax returns.', sourceName: 'Companies House', sourceUrl: 'https://www.gov.uk/running-a-limited-company/confirmation-statement', recurrence: 'annual'},
  ...['ENG', 'WLS', 'NIR'].map(region => ({country: 'GB', region, industry: 'FoodService', category: 'Registration', title: 'Register a food business with the local authority', description: 'Food businesses in England, Wales and Northern Ireland must register with the relevant local authority at least 28 days before trading. Multiple sites require registration with the authority for each site. Confirm whether your activities require registration or a different approval. Scotland has separate guidance.', sourceName: 'Food Standards Agency', sourceUrl: 'https://www.gov.uk/guidance/food-business-registration'})),
  {country: 'CA', region: '', industry: 'General', entityTypes: ['federalCorporation'], category: 'Registration', title: 'Federal corporation annual return', description: 'For a federally incorporated business corporation: file an annual return with Corporations Canada within 60 days of the incorporation, amalgamation or continuance anniversary. This is not a tax return. Provincially incorporated corporations follow their own registry requirements. Confirm any associated information filings with Corporations Canada.', sourceName: 'Corporations Canada', sourceUrl: 'https://www.ised-isde.canada.ca/site/corporations-canada/en/annual-return-versus-tax-return-they-are-not-same-thing', recurrence: 'annual'},
  {country: 'CA', region: 'BC', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'BC company annual report', description: 'For a company incorporated in British Columbia: file an annual report within two months of its incorporation anniversary. This entry is for BC companies, not federal corporations simply operating in BC. Confirm your registry record and deadline before adopting it.', sourceName: 'BC Registries', sourceUrl: 'https://www.corporateonline.gov.bc.ca/WebHelp/overview_annbc.htm', recurrence: 'annual'},
];
