import type {RuleScope} from '../src/jurisdictions';
/**
 * Sources individually checked 2026-09-18; rows carrying their own reviewedAt
 * were corrected after the 2026-09-19 source check
 * (docs/catalogue-review-2026-09-19.md). Selection is intentionally non-exhaustive.
 */
export const INTERNATIONAL_RULES: (RuleScope & {title: string; description: string; category: string; sourceName: string; sourceUrl: string; recurrence?: string; reviewedAt?: string})[] = [
  {country: 'AU', region: '', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'ASIC company annual review', description: 'For companies registered with ASIC: check the annual statement, pay the review fee by the date shown and check whether a solvency resolution is required. The fee is usually due two months after the review date. A financial-report exception can apply to the resolution. Use your own statement and the official guidance.', sourceName: 'ASIC', sourceUrl: 'https://www.asic.gov.au/for-business-and-companies/companies/company-annual-review/', recurrence: 'annual'},
  {country: 'AU', region: 'WA', industry: 'FoodService', category: 'Registration', title: 'WA food business registration or notification', description: 'Before operating, register or notify the relevant enforcement agency. Most food businesses deal with their local government; some are handled by WA Health. Exempt businesses may still need to notify. Registration generally continues until cancelled; do not assume an annual renewal. Check local fees and conditions separately.', sourceName: 'WA Department of Health', sourceUrl: 'https://www.health.wa.gov.au/articles/n_r/registration-of-a-food-business'},
  {country: 'AU', region: 'WA', locality: 'city-of-perth', industry: 'FoodService', category: 'Registration', title: 'City of Perth food premises approval', description: 'For premises inside the City of Perth council area, confirm whether registration or notification is required. New fit-outs and structural changes may need building or planning approval before food-business approval. Contact the City about the form appropriate to your premises. This does not cover the whole Perth metropolitan area.', sourceName: 'City of Perth', sourceUrl: 'https://perth.wa.gov.au/forms-and-payments/residents-and-businesses/Business/certification-and-approval/food-business-registration'},
  {country: 'GB', region: '', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'Companies House confirmation statement', description: 'For UK limited companies, including dormant ones: submit a confirmation statement at least once every twelve months, no later than 14 days after the review period ends. Before filing, every director must have verified their identity with Companies House; the statement asks for each director\'s personal code and a confirmation that they have verified. People with significant control must verify too, on a timetable that depends on their situation. This is separate from annual accounts and tax returns.', sourceName: 'Companies House — Confirmation statement guidance', sourceUrl: 'https://www.gov.uk/guidance/confirmation-statement-guidance', recurrence: 'annual', reviewedAt: '2026-09-19'},
  ...['ENG', 'WLS', 'NIR'].map(region => ({country: 'GB', region, industry: 'FoodService', category: 'Registration', title: 'Register a food business with the local authority', description: 'Food businesses in England, Wales and Northern Ireland must register with the relevant local authority at least 28 days before trading. Multiple sites require registration with the authority for each site. Confirm whether your activities require registration or a different approval. Scotland has separate guidance.', sourceName: 'Food Standards Agency', sourceUrl: 'https://www.gov.uk/guidance/food-business-registration'})),
  {country: 'GB', region: 'SCT', industry: 'FoodService', category: 'Registration', title: 'Register a food business with the local authority', description: 'Food businesses in Scotland, including those that only distribute food, must register with the environmental health service of their local authority at least 28 days before opening, and register every premises. Registration is free. Some businesses handling meat, fish, egg or dairy products for supply to other businesses need approval instead of registration.', sourceName: 'Food Standards Scotland', sourceUrl: 'https://www.foodstandards.gov.scot/business-guidance/starting-a-new-business/registering-a-food-business', reviewedAt: '2026-09-19'},
  {country: 'CA', region: '', industry: 'General', entityTypes: ['federalCorporation'], category: 'Registration', title: 'Federal corporation annual return', description: 'For a federally incorporated business corporation: file an annual return with Corporations Canada within 60 days of the incorporation, amalgamation or continuance anniversary, and file information on individuals with significant control at the same time. This is not a tax return. Not filing can lead to the corporation being dissolved. Provincially incorporated corporations follow their own registry requirements.', sourceName: 'Corporations Canada — Annual return for business corporations', sourceUrl: 'https://ised-isde.canada.ca/site/corporations-canada/en/annual-return-business-corporations', recurrence: 'annual', reviewedAt: '2026-09-19'},
  {country: 'CA', region: 'BC', industry: 'General', entityTypes: ['company'], category: 'Registration', title: 'BC company annual report', description: 'For a company incorporated in British Columbia: file an annual report within two months of its incorporation anniversary. This entry is for BC companies, not federal corporations simply operating in BC. Confirm your registry record and deadline before adopting it.', sourceName: 'BC Registries', sourceUrl: 'https://www.corporateonline.gov.bc.ca/WebHelp/overview_annbc.htm', recurrence: 'annual'},
];
