default_platform(:ios)
platform :ios do
  lane :release do
    increment_build_number(build_number: ENV.fetch('BUILD_NUMBER', Time.now.strftime('%Y%m%d%H%M')))
    build_app(scheme: 'ComplianceCalendar', export_method: 'app-store')
    upload_to_app_store(skip_waiting_for_build_processing: true)
  end
end
platform :android do
  lane :release do
    gradle(task: 'bundle', flavor: 'Release', project_dir: 'android')
    upload_to_play_store(track: ENV.fetch('PLAY_TRACK', 'internal'), aab: 'android/app/build/outputs/bundle/release/app-release.aab')
  end
end
