/** Spanish UI for US/UK obligations. Legal source documents keep their original language. */
export const spanish = {
  appName: 'OBLIGIO', dashboard: 'Tu panel', calendar: 'Calendario', documents: 'Documentos', settings: 'Ajustes',
  crashTitle: 'Se produjo un error.', crashBody: 'Obligio se detuvo por un error inesperado. Tus obligaciones y documentos se guardan en nuestros servidores.',
  businessProfile: 'Perfil del negocio', privacyAndData: 'Privacidad y datos', helpAndSupport: 'Ayuda y soporte',
  deleteAccount: 'Eliminar cuenta', deleteAccountHint: 'Elimina permanentemente tus negocios, obligaciones y documentos',
  deleteAccountTitle: '¿Eliminar tu cuenta?',
  deleteAccountBody: 'Esta acción elimina permanentemente tus negocios, todas las obligaciones que sigues y todos los documentos adjuntos. No se puede deshacer.\n\nSi tienes una suscripción de pago, cancélala también en App Store o Google Play. Eliminar tu cuenta aquí no cancela la suscripción.',
  deleteAccountConfirm: 'Eliminar todo', deleteAccountCancel: 'Cancelar',
  deleteAccountFailed: 'No se completó la eliminación. Es posible que algunos datos ya se hayan eliminado. Vuelve a intentarlo o escribe a privacy@obligio.com.',
  complianceHealth: 'Estado de cumplimiento', scoreHintClear: 'Todo está al día.',
  scoreHint: (count: number) => `Resuelve ${count} ${count === 1 ? 'pendiente' : 'pendientes'} para llegar al 100%`,
  current: 'Al día', upcoming: 'Próxima', overdue: 'Vencida', attention: 'Requiere atención', viewAll: 'Ver todo',
  addRequirement: 'Añadir obligación', disclaimer: 'Obligio ofrece herramientas de organización, no asesoramiento legal ni fiscal.',
  sampleData: 'Datos de ejemplo. Inicia sesión para seguir tus propias obligaciones.',
  signInRequired: 'Inicia sesión para configurar tu negocio.', signIn: 'Iniciar sesión', tryAgain: 'Reintentar', close: 'Cerrar',
  noRequirements: 'Aún no tienes obligaciones. Añade la primera para comenzar.', organisational: 'organizativo',
  documentsHelper: 'Sube certificados de seguro, licencias, permisos y registros de formación. Quedan vinculados a su obligación; abre una obligación para adjuntar documentos.',
  signInTitle: 'Las obligaciones de tu negocio, bajo control.',
  signInBody: 'Organiza licencias, seguros, declaraciones, inspecciones y documentos en un solo lugar.',
  signInCta: 'Inicia sesión para comenzar', signInWithApple: 'Iniciar sesión con Apple', signingIn: 'Abriendo inicio de sesión…',
  authUnavailable: 'El inicio de sesión no está disponible',
  authUnavailableBody: 'Esta versión no puede acceder a tu cuenta. Lo que se muestra son datos de ejemplo.',
  signOut: 'Cerrar sesión', checkingSession: 'Comprobando tu sesión…',
  onboardingTitle: 'Cuéntanos sobre tu negocio', onboardingBody: 'Tu ubicación y sector determinan las obligaciones sugeridas.',
  businessName: 'Nombre del negocio', country: 'País', region: 'Estado o región', industry: 'Sector',
  createBusiness: 'Crear mi negocio', creatingBusiness: 'Creando…', suggested: 'Sugerencias para ti', suggestedTitle: 'Obligaciones sugeridas',
  suggestedBody: 'Obligaciones habituales según tu ubicación y sector. Algunas sugerencias y fuentes permanecen en inglés. Consulta la fuente oficial antes de basarte en una sugerencia.',
  suggestedEmpty: 'Aún no hay sugerencias para tu ubicación y sector. Puedes añadir obligaciones manualmente.',
  suggestedDateHint: 'Los plazos dependen de la entidad y su historial. Indica la fecha que corresponda a tu negocio.',
  trackThis: 'Seguir obligación', source: 'Fuente', reviewed: 'revisado', editRequirement: 'Editar obligación',
  saveRequirement: 'Guardar obligación', saving: 'Guardando…', removing: 'Eliminando…', uploading: 'Subiendo…', opening: 'Abriendo…',
  viewEvidence: 'Ver documento', attachEvidence: 'Adjuntar documento', replaceEvidence: 'Reemplazar documento',
  markDoneNext: 'Completar y programar siguiente', markCurrent: 'Marcar al día', deleteObligation: 'Eliminar obligación',
  noEvidence: 'Esta obligación no tiene documentos adjuntos.', plusRequired: 'Obligio Plus',
  freeLimitReached: (limit: number) => `El plan gratuito permite seguir ${limit} obligaciones. Mejora tu plan para añadir más.`,
  evidenceIsPlus: 'Adjuntar documentos forma parte de Obligio Plus.', recurrenceIsPlus: 'Las obligaciones recurrentes forman parte de Obligio Plus.',
  plusActive: 'Obligio Plus está activo', upgrade: 'Mejorar plan',
  text: (source: string): string => spanishText[source] ?? source,
};

const spanishText: Record<string, string> = {
  'Use your registered jurisdiction. Suggestions cover one location; add obligations for other operating locations manually.': 'Usa la jurisdicción de registro. Las sugerencias cubren una ubicación; añade manualmente las obligaciones de otras ubicaciones.',
  'United Kingdom': 'Reino Unido', 'Australia': 'Australia', 'Canada': 'Canadá', 'UK-wide': 'Todo el Reino Unido', 'Region not selected': 'Región sin seleccionar',
  'Provincially incorporated corporation': 'Sociedad constituida a nivel provincial', 'Local authority': 'Autoridad local', 'Entity type': 'Tipo de entidad', 'Other / not selected': 'Otra / sin seleccionar', 'Not sure / other': 'No sé / otra', 'Sole trader': 'Empresario individual', 'Company / corporation': 'Sociedad', 'Federally incorporated business corporation': 'Sociedad constituida a nivel federal', 'City of Perth (council area)': 'Ciudad de Perth (municipio)',
  'Save business profile': 'Guardar perfil del negocio', 'Open official source': 'Abrir fuente oficial', 'Could not open the official source.': 'No se pudo abrir la fuente oficial.',
  'Changing your profile updates suggestions only. Review existing obligations separately.': 'Cambiar el perfil solo actualiza las sugerencias. Revisa las obligaciones existentes por separado.',
  'Selected requirements only. Local rules and eligibility may be missing. An empty list does not mean no obligations apply. Confirm requirements with the authority; add other obligations manually.': 'Solo requisitos seleccionados. Pueden faltar normas locales y criterios de aplicación. Una lista vacía no significa que no haya obligaciones. Confirma con la autoridad y añade las demás manualmente.',

  'Test reminder status': 'Estado del recordatorio de prueba',
  'Delivered: your test reminder is in Notification Centre.': 'Entregado: el recordatorio de prueba está en el centro de notificaciones.',
  'No test reminder is currently displayed. It may still be waiting or may have been dismissed.': 'No se muestra ningún recordatorio de prueba. Puede estar pendiente o haberse descartado.',
  'Home': 'Inicio', 'Calendar': 'Calendario', 'Docs': 'Docs', 'Settings': 'Ajustes',
  'Notification preferences': 'Preferencias de notificación', 'Deadline reminders are on': 'Recordatorios activados',
  'Tap to enable deadline reminders': 'Toca para activar los recordatorios', 'Send test reminder': 'Enviar recordatorio de prueba',
  'Check delivery in one minute': 'Comprueba la recepción en un minuto', 'Subscription': 'Suscripción',
  'Obligio Plus is active': 'Obligio Plus está activo', 'Free plan — tap to see Obligio Plus': 'Plan gratuito: consulta Obligio Plus',
  'Plans are not available in this build': 'Los planes no están disponibles en esta versión',
  'Upcoming deadlines are grouped by month.': 'Los próximos plazos se agrupan por mes.', 'ATTACHED': 'ADJUNTOS', 'MISSING EVIDENCE': 'SIN DOCUMENTOS',
  'Requirement name': 'Nombre de la obligación', 'Category (e.g. Insurance)': 'Categoría (p. ej., Seguros)',
  'Enter a real date, for example': 'Introduce una fecha válida, por ejemplo', 'Saving as': 'Se guardará como', 'REPEATS': 'REPETICIÓN',
  'Monthly': 'Mensual', 'Quarterly': 'Trimestral', 'Annual': 'Anual', 'Every 2 years': 'Cada 2 años', 'Every 3 years': 'Cada 3 años', 'Every 5 years': 'Cada 5 años', 'One-off': 'Una sola vez',
  'monthly': 'mensual', 'quarterly': 'trimestral', 'annual': 'anual', 'every 2 years': 'cada 2 años', 'every 3 years': 'cada 3 años', 'every 5 years': 'cada 5 años',
  'Overdue — action required': 'Vencida: requiere atención', 'Upcoming — prepare to renew': 'Próxima: prepara la renovación', 'Current — monitored': 'Al día',
  'Obligation detail': 'Detalle de la obligación', 'Due': 'Vence', 'Repeats': 'Repetición', 'Next action': 'Siguiente acción',
  'Resolve this obligation and attach current evidence.': 'Resuelve esta obligación y adjunta documentos vigentes.',
  'Review the requirement before its due date.': 'Revisa la obligación antes de su vencimiento.',
  'Obligio Plus is active.': 'Obligio Plus está activo.', 'Purchase completed, but the entitlement is not active yet.': 'Compra completada. El acceso aún no está activo.',
  'Obligio Plus restored.': 'Se restauró Obligio Plus.', 'No previous purchase was found for this account.': 'No se encontraron compras anteriores en esta cuenta.',
  'Your account has access to unlimited obligations, document evidence and recurring reminders.': 'Tu cuenta permite seguir obligaciones ilimitadas, adjuntar documentos y usar recordatorios recurrentes.',
  'If you have a paid subscription, manage or cancel it in your App Store or Google Play account. Deleting your Obligio account does not cancel a store subscription.': 'Gestiona o cancela tu suscripción de pago en App Store o Google Play. Eliminar tu cuenta de Obligio no cancela la suscripción.',
  'Done': 'Listo', 'Stay ahead with Obligio Plus': 'Anticípate con Obligio Plus',
  'Unlimited obligations, document evidence, recurring reminders, and a clearer compliance view for your business.': 'Obligaciones ilimitadas, documentos adjuntos, recordatorios recurrentes y una visión más clara del cumplimiento de tu negocio.',
  'Plans are not available in this build. A RevenueCat store key has not been configured yet.': 'Los planes no están disponibles en esta versión.',
  'No subscription plans are currently offered for your store account.': 'No hay planes disponibles para tu cuenta de la tienda.',
  'Working…': 'Procesando…', 'Subscribe': 'Suscribirse', 'Restore purchases': 'Restaurar compras',
  'Subscriptions are managed through the App Store or Google Play. See Privacy and Terms.': 'Las suscripciones se gestionan en App Store o Google Play. Consulta la privacidad y las condiciones.',
  'Test reminder scheduled': 'Recordatorio de prueba programado',
  'Lock your phone. A test reminder should arrive in about one minute.': 'Bloquea el teléfono. El recordatorio de prueba debería llegar en un minuto.',
  'United States': 'Estados Unidos', 'Federal only': 'Solo obligaciones federales', 'General business': 'Negocios en general',
  'Food & beverage': 'Alimentos y bebidas', 'Retail': 'Comercio minorista', 'Construction & trades': 'Construcción y oficios', 'Health & care': 'Salud y cuidados',
  'Childcare & education': 'Cuidado infantil y educación', 'Transport & logistics': 'Transporte y logística', 'Professional services': 'Servicios profesionales',
  'Beauty & personal care': 'Belleza y cuidado personal', 'Fitness & recreation': 'Deporte y recreación',
  'Obligio logo': 'Logotipo de Obligio', 'evidence attached': 'documento adjunto', 'percent compliance health': 'por ciento de cumplimiento',
};
