import {StyleSheet} from 'react-native';
import {colors} from './designTokens';

/** Shared styles for the app shell, screens, and modals. */
export const s = StyleSheet.create({
  safe: {flex: 1, backgroundColor: colors.canvas},
  container: {padding: 24, paddingBottom: 100},
  top: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 24},
  eyebrow: {fontSize: 13, fontWeight: '700', letterSpacing: 1.4, color: colors.sage500},
  title: {fontSize: 32, fontWeight: '800', color: colors.forest900, marginTop: 5},
  locale: {borderWidth: 1, borderColor: '#CAD5CE', borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8},
  localeText: {fontWeight: '700', color: '#305347'},

  scoreCard: {
    backgroundColor: colors.forest800,
    borderRadius: 24,
    padding: 24,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  score: {fontSize: 50, fontWeight: '800', color: colors.white},
  scoreLabel: {fontSize: 16, fontWeight: '700', color: '#DDEBE3', marginTop: -4},
  darkMuted: {fontSize: 13, color: '#BBD8C8', marginTop: 4},
  ring: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 7,
    borderColor: '#82C6A7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ringText: {fontSize: 32, color: colors.white},

  stats: {flexDirection: 'row', backgroundColor: colors.white, borderRadius: 18, padding: 18, marginTop: 14, marginBottom: 30},
  stat: {flex: 1},
  statValue: {fontSize: 24, fontWeight: '800'},
  muted: {fontSize: 13, color: '#6C7D74', marginTop: 4},

  sectionHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12},
  sectionTitle: {fontSize: 20, fontWeight: '800', color: colors.forest900},
  monthHeading: {fontSize: 14, fontWeight: '800', color: colors.sage500, letterSpacing: 0.6, marginTop: 18, marginBottom: 8},
  link: {fontSize: 14, fontWeight: '700', color: colors.forest600},
  linkSpaced: {fontSize: 14, fontWeight: '700', color: colors.forest600, marginTop: 8},
  noticeText: {fontSize: 13, marginTop: 4, color: colors.forest600, fontWeight: '700'},

  item: {flexDirection: 'row', alignItems: 'center', backgroundColor: colors.white, borderRadius: 16, padding: 16, marginBottom: 10},
  dot: {width: 10, height: 10, borderRadius: 5, marginRight: 14},
  currentDot: {backgroundColor: colors.forest600},
  upcomingDot: {backgroundColor: '#D88A11'},
  overdueDot: {backgroundColor: '#C6382B'},
  itemBody: {flex: 1},
  itemTitle: {fontSize: 16, fontWeight: '700', color: '#173126'},
  chevron: {fontSize: 28, color: '#83918A'},
  paperclip: {fontSize: 14, color: colors.forest600, marginRight: 8},

  primary: {backgroundColor: colors.mint100, borderRadius: 16, alignItems: 'center', padding: 17, marginTop: 10},
  primaryText: {color: '#14593E', fontSize: 16, fontWeight: '800'},
  primaryDisabled: {opacity: 0.5},
  secondary: {borderWidth: 1, borderColor: colors.forest600, borderRadius: 16, alignItems: 'center', padding: 16, marginTop: 10},
  secondaryText: {color: colors.forest600, fontSize: 16, fontWeight: '800'},
  destructiveText: {color: colors.red700, fontSize: 15, fontWeight: '700', textAlign: 'center', marginTop: 16},

  disclaimer: {fontSize: 11, color: '#829088', textAlign: 'center', lineHeight: 16, marginTop: 22},
  banner: {backgroundColor: '#FFF4E0', borderRadius: 12, padding: 12, marginBottom: 16},
  bannerText: {fontSize: 13, color: '#7A4E00', fontWeight: '600'},
  errorBox: {backgroundColor: '#FDECEA', borderRadius: 12, padding: 14, marginTop: 14},
  errorText: {fontSize: 14, color: colors.red700, fontWeight: '600'},

  welcome: {flex: 1, padding: 28, justifyContent: 'center'},
  logo: {width: 72, height: 72, alignItems: 'center', justifyContent: 'center', marginBottom: 28},
  logoText: {fontSize: 40, color: colors.mint100},
  welcomeTitle: {letterSpacing: -2, color: colors.forest800, marginTop: 14},
  welcomeBody: {color: colors.sage500, lineHeight: 28, marginTop: 24, marginBottom: 28},

  nav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 78,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: '#E0E7E2',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingTop: 10,
  },
  navItem: {alignItems: 'center', flex: 1},
  navIcon: {fontSize: 22, color: '#83918A'},
  navLabel: {fontSize: 11, color: '#83918A', marginTop: 3},
  navActive: {color: colors.forest600, fontWeight: '800'},

  helper: {fontSize: 15, color: '#6C7D74', lineHeight: 23, marginBottom: 18},
  empty: {backgroundColor: colors.white, borderRadius: 20, padding: 24, alignItems: 'center'},
  emptyIcon: {fontSize: 42, color: colors.forest600, marginBottom: 10},
  setting: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },

  modal: {position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(19,37,29,.45)', justifyContent: 'flex-end'},
  modalCard: {backgroundColor: colors.canvas, borderTopLeftRadius: 26, borderTopRightRadius: 26, padding: 24, paddingBottom: 34},
  input: {backgroundColor: colors.white, borderRadius: 12, padding: 16, fontSize: 16, marginBottom: 12, color: '#173126'},
  inputInvalid: {borderWidth: 1, borderColor: colors.red700},
  detailTitle: {fontSize: 28, fontWeight: '800', color: colors.forest800, marginTop: 14, marginBottom: 10},
  detailStatus: {fontSize: 15, fontWeight: '700', color: colors.amber700, marginBottom: 8},
  detailStatusCurrent: {color: colors.forest600},
  detailCard: {backgroundColor: colors.white, borderRadius: 16, padding: 16, marginTop: 8},
  choice: {backgroundColor: colors.white, borderRadius: 14, padding: 14, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  choiceSelected: {borderWidth: 2, borderColor: colors.forest600},
  chip: {borderWidth: 1, borderColor: '#CAD5CE', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8, marginRight: 8, marginBottom: 8},
  chipSelected: {backgroundColor: colors.mint100, borderColor: colors.forest600},
  chipText: {fontSize: 13, fontWeight: '700', color: '#305347'},
  row: {flexDirection: 'row', flexWrap: 'wrap'},
});
